#! /bin/sh
userdel -r dejunious
userdel -r nunezgomez
userdel -r uellaegoess
userdel -r lanpher
userdel -r galvin
userdel -r laspina
userdel -r dodich
userdel -r bannowsky
userdel -r waisath
userdel -r vonreddigpiette
userdel -r latona
userdel -r homewood
userdel -r pallaforzedian
userdel -r senemounnaratquillian
userdel -r isaac
userdel -r plancarte
userdel -r berteottistirn
userdel -r strycker
userdel -r vonverrill
userdel -r deschner
userdel -r franzi
userdel -r cringle
userdel -r kosh
userdel -r derouchie
userdel -r doutt
userdel -r munley
userdel -r dornbos
userdel -r mahala
userdel -r ellingwood
userdel -r decardinallisciola
userdel -r gundry
userdel -r pinedo
userdel -r faivre
userdel -r pinsky
userdel -r pinsky1
userdel -r pinsky2
userdel -r pinsky3
